/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/fusioninfer/fusioninfer/api/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ComponentStatusApplyConfiguration represents a declarative configuration of the ComponentStatus type for use
// with apply.
//
// ComponentStatus captures the aggregated runtime state of a single inference component (role).
// For example, with replicas=2 and multinode.nodeCount=4:
// - DesiredReplicas: 2
// - NodesPerReplica: 4
// - TotalPods: 8 (2 * 4)
// - ReadyReplicas: 0/1/2 (a replica is ready only when all its nodes are ready)
// - ReadyPods: 0-8
type ComponentStatusApplyConfiguration struct {
	// DesiredReplicas is the number of replicas requested (from spec.roles[].replicas).
	DesiredReplicas *int32 `json:"desiredReplicas,omitempty"`
	// ReadyReplicas is the number of replicas that are fully ready.
	// For multi-node replicas, a replica is ready only when all its nodes are ready.
	ReadyReplicas *int32 `json:"readyReplicas,omitempty"`
	// NodesPerReplica is the number of nodes per replica (from spec.roles[].multinode.nodeCount).
	// Defaults to 1 when multinode is not configured.
	NodesPerReplica *int32 `json:"nodesPerReplica,omitempty"`
	// TotalPods is the total number of pods desired (= DesiredReplicas * NodesPerReplica).
	TotalPods *int32 `json:"totalPods,omitempty"`
	// ReadyPods is the total number of ready pods across all replicas.
	ReadyPods *int32 `json:"readyPods,omitempty"`
	// Phase indicates the high-level lifecycle stage of this component.
	// Possible values: Pending, Deploying, Running, Failed, Unknown.
	Phase *corev1alpha1.ComponentPhase `json:"phase,omitempty"`
	// LastUpdateTime is the timestamp when this component's status was last updated.
	LastUpdateTime *v1.Time `json:"lastUpdateTime,omitempty"`
}

// ComponentStatusApplyConfiguration constructs a declarative configuration of the ComponentStatus type for use with
// apply.
func ComponentStatus() *ComponentStatusApplyConfiguration {
	return &ComponentStatusApplyConfiguration{}
}

// WithDesiredReplicas sets the DesiredReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DesiredReplicas field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithDesiredReplicas(value int32) *ComponentStatusApplyConfiguration {
	b.DesiredReplicas = &value
	return b
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithReadyReplicas(value int32) *ComponentStatusApplyConfiguration {
	b.ReadyReplicas = &value
	return b
}

// WithNodesPerReplica sets the NodesPerReplica field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodesPerReplica field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithNodesPerReplica(value int32) *ComponentStatusApplyConfiguration {
	b.NodesPerReplica = &value
	return b
}

// WithTotalPods sets the TotalPods field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TotalPods field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithTotalPods(value int32) *ComponentStatusApplyConfiguration {
	b.TotalPods = &value
	return b
}

// WithReadyPods sets the ReadyPods field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyPods field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithReadyPods(value int32) *ComponentStatusApplyConfiguration {
	b.ReadyPods = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithPhase(value corev1alpha1.ComponentPhase) *ComponentStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithLastUpdateTime sets the LastUpdateTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastUpdateTime field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithLastUpdateTime(value v1.Time) *ComponentStatusApplyConfiguration {
	b.LastUpdateTime = &value
	return b
}
