/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ModelSpecApplyConfiguration represents a declarative configuration of the ModelSpec type for use
// with apply.
//
// ModelSpec declares a model artifact and the nodes to prefetch it to.
type ModelSpecApplyConfiguration struct {
	// Source identifies where the model artifact is stored.
	Source *ModelSourceApplyConfiguration `json:"source,omitempty"`
	// LoRA identifies this artifact as a LoRA adapter and names its Base Model.
	LoRA *LoRAArtifactSpecApplyConfiguration `json:"lora,omitempty"`
	// Prefetch declares the nodes to download the model to before it is needed.
	// When omitted, the model is downloaded on demand.
	Prefetch *PrefetchSpecApplyConfiguration `json:"prefetch,omitempty"`
}

// ModelSpecApplyConfiguration constructs a declarative configuration of the ModelSpec type for use with
// apply.
func ModelSpec() *ModelSpecApplyConfiguration {
	return &ModelSpecApplyConfiguration{}
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *ModelSpecApplyConfiguration) WithSource(value *ModelSourceApplyConfiguration) *ModelSpecApplyConfiguration {
	b.Source = value
	return b
}

// WithLoRA sets the LoRA field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LoRA field is set to the value of the last call.
func (b *ModelSpecApplyConfiguration) WithLoRA(value *LoRAArtifactSpecApplyConfiguration) *ModelSpecApplyConfiguration {
	b.LoRA = value
	return b
}

// WithPrefetch sets the Prefetch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefetch field is set to the value of the last call.
func (b *ModelSpecApplyConfiguration) WithPrefetch(value *PrefetchSpecApplyConfiguration) *ModelSpecApplyConfiguration {
	b.Prefetch = value
	return b
}
