/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ModelSourceApplyConfiguration represents a declarative configuration of the ModelSource type for use
// with apply.
//
// ModelSource declares where a model artifact is stored and the Secret used to access it.
type ModelSourceApplyConfiguration struct {
	// URI is the model artifact location. The version, when present, is part of the URI:
	// hf://<owner>/<repo>[@<revision>], s3://<bucket>/<prefix>, or
	// oci://<registry>/<repository>[:<tag>|@sha256:<digest>].
	URI *string `json:"uri,omitempty"`
	// CredentialsRef names the Secret used to access the source.
	// When omitted, the source is accessed anonymously.
	CredentialsRef *SecretReferenceApplyConfiguration `json:"credentialsRef,omitempty"`
}

// ModelSourceApplyConfiguration constructs a declarative configuration of the ModelSource type for use with
// apply.
func ModelSource() *ModelSourceApplyConfiguration {
	return &ModelSourceApplyConfiguration{}
}

// WithURI sets the URI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URI field is set to the value of the last call.
func (b *ModelSourceApplyConfiguration) WithURI(value string) *ModelSourceApplyConfiguration {
	b.URI = &value
	return b
}

// WithCredentialsRef sets the CredentialsRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CredentialsRef field is set to the value of the last call.
func (b *ModelSourceApplyConfiguration) WithCredentialsRef(value *SecretReferenceApplyConfiguration) *ModelSourceApplyConfiguration {
	b.CredentialsRef = value
	return b
}
