/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PrefetchSpecApplyConfiguration represents a declarative configuration of the PrefetchSpec type for use
// with apply.
//
// PrefetchSpec declares the nodes to download a model to before it is needed.
// An empty PrefetchSpec selects every node that runs the model agent.
type PrefetchSpecApplyConfiguration struct {
	// NodeSelector selects the nodes whose labels match all of the given labels.
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
	// NodeName selects a single node by name.
	NodeName *string `json:"nodeName,omitempty"`
}

// PrefetchSpecApplyConfiguration constructs a declarative configuration of the PrefetchSpec type for use with
// apply.
func PrefetchSpec() *PrefetchSpecApplyConfiguration {
	return &PrefetchSpecApplyConfiguration{}
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *PrefetchSpecApplyConfiguration) WithNodeSelector(entries map[string]string) *PrefetchSpecApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithNodeName sets the NodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeName field is set to the value of the last call.
func (b *PrefetchSpecApplyConfiguration) WithNodeName(value string) *PrefetchSpecApplyConfiguration {
	b.NodeName = &value
	return b
}
