/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PrefetchStatusApplyConfiguration represents a declarative configuration of the PrefetchStatus type for use
// with apply.
type PrefetchStatusApplyConfiguration struct {
	DesiredNodes *int32 `json:"desiredNodes,omitempty"`
	ReadyNodes   *int32 `json:"readyNodes,omitempty"`
	FailedNodes  *int32 `json:"failedNodes,omitempty"`
}

// PrefetchStatusApplyConfiguration constructs a declarative configuration of the PrefetchStatus type for use with
// apply.
func PrefetchStatus() *PrefetchStatusApplyConfiguration {
	return &PrefetchStatusApplyConfiguration{}
}

// WithDesiredNodes sets the DesiredNodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DesiredNodes field is set to the value of the last call.
func (b *PrefetchStatusApplyConfiguration) WithDesiredNodes(value int32) *PrefetchStatusApplyConfiguration {
	b.DesiredNodes = &value
	return b
}

// WithReadyNodes sets the ReadyNodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyNodes field is set to the value of the last call.
func (b *PrefetchStatusApplyConfiguration) WithReadyNodes(value int32) *PrefetchStatusApplyConfiguration {
	b.ReadyNodes = &value
	return b
}

// WithFailedNodes sets the FailedNodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedNodes field is set to the value of the last call.
func (b *PrefetchStatusApplyConfiguration) WithFailedNodes(value int32) *PrefetchStatusApplyConfiguration {
	b.FailedNodes = &value
	return b
}
